<?php 

 return [
     "home" => "Inicio",
     "blogs" => "Blog",
     "helps" => "Ayuda",
     "current_location" => "ubicación actual",
     "dashboard" => "panel de control",
     "my_shops" => "Mis tiendas",
     "wallet" => "wallet",
     "about" => "Acerca de Selldone",
     "contact" => "contacto",
     "comments" => "comentarios",
     "likes" => "Me gusta",
     "power" => "alegría",
     "build_free_shop" => "Crea tu tienda gratis",
     "shop_name" => "shop name",
     "categories" => "categorías",
     "sub_articles" => "sub artículos",
     "terms" => "Términos",
     "colour" => "color",
     "style" => "estilo",
     "volume" => "volumen",
     "weight" => "peso",
     "pack" => "Paquete",
     "type" => "tipo",
     "add_to_card" => "Añadir al carrito",
     "overview" => "Overview",
     "reviews" => "Reseñas",
     "spec" => "especificaciones completas",
     "you_may_also_like" => "También te puede interesar",
     "about_us" => "Sobre nosotros",
     "contact_us" => "contact us",
     "cookie_privacy" => "Cookie &amp; privacy policy",
     "follow_us" => "Síganos",
     "category" => "Categoría",
     "author" => "Escrito por",
     "published_at" => "Publicado en",
     "modified_at" => "Modificado en",
     "price" => "precio",
     "discount" => "Descuento",
     "price_after_discount" => "Precio después del descuento",
     "available" => "Disponible",
     "sold_out" => "Agotado",
     "buy" => "Compra ahora",
     "login_shop" => "Entrar Tienda",
     "posted_on" => "Publicado el :fecha",
];
